// Catégories prédéfinies : listes de domaines curées, référencées dans les
// cibles d'une règle par un jeton « @id » (ex. "@social"). Le jeton est stocké
// tel quel dans rule.targets et résolu à chaque parsing : une mise à jour de
// ces listes profite automatiquement aux règles existantes.
//
// Domaines uniquement (les sous-domaines sont couverts par le matching) ;
// les listes visent les sites majeurs — internationaux d'abord, plus les
// incontournables locaux (FR aujourd'hui) — pas l'exhaustivité :
// l'utilisateur peut toujours compléter cible par cible.

export const CATEGORIES = {
  social: [
    'facebook.com',
    'instagram.com',
    'tiktok.com',
    'douyin.com',
    'x.com',
    'twitter.com',
    'snapchat.com',
    'reddit.com',
    'threads.net',
    'pinterest.com',
    'tumblr.com',
    'bsky.app',
    'mastodon.social',
    'discord.com',
    'vk.com',
    'weibo.com',
    '9gag.com',
  ],
  video: [
    'youtube.com',
    'twitch.tv',
    'kick.com',
    'netflix.com',
    'primevideo.com',
    'disneyplus.com',
    'max.com',
    'hulu.com',
    'dailymotion.com',
    'vimeo.com',
    'crunchyroll.com',
    'bilibili.com',
    'nicovideo.jp',
    'rumble.com',
  ],
  news: [
    'lemonde.fr',
    'lefigaro.fr',
    'liberation.fr',
    'leparisien.fr',
    'bfmtv.com',
    'francetvinfo.fr',
    '20minutes.fr',
    'cnews.fr',
    'news.google.com',
    'bbc.com',
    'bbc.co.uk',
    'cnn.com',
    'nytimes.com',
    'theguardian.com',
    'washingtonpost.com',
    'foxnews.com',
    'dailymail.co.uk',
    'spiegel.de',
    'bild.de',
    'elpais.com',
    'corriere.it',
    'aljazeera.com',
    'reuters.com',
  ],
  shopping: [
    'amazon.fr',
    'amazon.com',
    'amazon.de',
    'amazon.co.uk',
    'aliexpress.com',
    'alibaba.com',
    'temu.com',
    'shein.com',
    'vinted.fr',
    'ebay.fr',
    'ebay.com',
    'cdiscount.com',
    'leboncoin.fr',
    'etsy.com',
    'wish.com',
    'walmart.com',
    'target.com',
    'rakuten.com',
    'mercadolibre.com',
    'asos.com',
    'zalando.fr',
  ],
  adult: [
    'pornhub.com',
    'xvideos.com',
    'xnxx.com',
    'xhamster.com',
    'redtube.com',
    'youporn.com',
    'spankbang.com',
    'eporner.com',
    'hqporner.com',
    'tnaflix.com',
    'motherless.com',
    'rule34.xxx',
    'nhentai.net',
    'onlyfans.com',
    'fansly.com',
    'chaturbate.com',
    'stripchat.com',
    'livejasmin.com',
    'bongacams.com',
    'cam4.com',
    'myfreecams.com',
  ],
  gambling: [
    'winamax.fr',
    'betclic.fr',
    'unibet.fr',
    'unibet.com',
    'pmu.fr',
    'zebet.fr',
    'fdj.fr',
    'pokerstars.fr',
    'pokerstars.com',
    'bwin.fr',
    'bwin.com',
    'bet365.com',
    'stake.com',
    'netbet.fr',
    '888.com',
    'williamhill.com',
    'ladbrokes.com',
    'paddypower.com',
    'betway.com',
    'draftkings.com',
    'fanduel.com',
    '1xbet.com',
    'roobet.com',
  ],
};

/**
 * Identifiant de catégorie si `raw` est un jeton "@id" connu, sinon null.
 * Tolère espaces et majuscules ("@Social " → "social").
 */
export function categoryId(raw) {
  const m = /^@([a-z]+)$/.exec(String(raw ?? '').trim().toLowerCase());
  return m && CATEGORIES[m[1]] ? m[1] : null;
}
